plugins { id 'com.android.application' }

android { namespace 'ir.keynu.hormuzmines'; compileSdk 35
    defaultConfig { applicationId 'ir.keynu.hormuzmines'; minSdk 23; targetSdk 35; versionCode 1; versionName '1.0.0' }
    buildTypes { release { minifyEnabled true; shrinkResources true; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } }
}


dependencies {
    implementation 'com.google.android.gms:play-services-ads:24.5.0'
}
